version: "3"

services:
    mongodb:
        image: mongo:5.0.2
        restart: unless-stopped
        ports:
            - $MONGO_PORT:$MONGO_PORT
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        volumes:
            - db:/data/db
        networks:
            - backend

    server:
        depends_on:
            - mongodb
        build:
            context: ./server
        restart: unless-stopped
        ports:
            - $HOST_PORT:$SERVER_PORT
        environment:
            - SERVER_PORT=$SERVER_PORT
            - MONGODB_USER=$MONGODB_USER
            - MONGODB_PASSWORD=$MONGODB_PASSWORD
            - MONGODB_DATABASE=$MONGODB_DATABASE
            - MONGODB_HOST=$MONGODB_HOST
            - MONGO_PORT=$MONGO_PORT
            - JWT_SECRET=$JWT_SECRET
        networks:
            - backend

volumes:
    db:

networks:
    backend:
