version: "3"

services:
    server:
        build:
            context: ./server
            target: dev
        volumes:
            - ./server:/server:ro
            - /server/node_modules
        environment:
            - NODE_ENV=development
